class Theme:
    LIGHT: dict = {
        "bg":           "#F0F4F8",
        "panel":        "#FFFFFF",
        "panel_border": "#DDE3EA",
        "clock_face":   "#FAFBFC",
        "clock_border": "#2D3A4A",
        "numbers":      "#2D3A4A",
        "tick_hour":    "#2D3A4A",
        "tick_min":     "#A0AABB",
        "hand_hour":    "#1A2433",
        "hand_min":     "#2D3A4A",
        "hand_sec":     "#E63946",
        "pivot":        "#E63946",
        "shadow":       "#C8D0DA",
        "text":         "#2D3A4A",
        "subtext":      "#5A6A7A",
        "btn_bg":       "#2D3A4A",
        "btn_fg":       "#FFFFFF",
        "accent":       "#E63946",
        "input_bg":     "#FFFFFF",
        "input_fg":     "#2D3A4A",
        "spin_bg":      "#FFFFFF",
        "spin_fg":      "#2D3A4A",
        "list_bg":      "#F5F7FA",
        "list_fg":      "#2D3A4A",
        "list_sel":     "#E63946",
    }

    DARK: dict = {
        "bg":           "#0F1923",
        "panel":        "#1A2535",
        "panel_border": "#253548",
        "clock_face":   "#1E2D40",
        "clock_border": "#4A90D9",
        "numbers":      "#C8D8E8",
        "tick_hour":    "#4A90D9",
        "tick_min":     "#2A4A6A",
        "hand_hour":    "#E8F0FA",
        "hand_min":     "#C8D8E8",
        "hand_sec":     "#FF6B6B",
        "pivot":        "#FF6B6B",
        "shadow":       "#0A1218",
        "text":         "#C8D8E8",
        "subtext":      "#6A8AAA",
        "btn_bg":       "#4A90D9",
        "btn_fg":       "#0F1923",
        "accent":       "#FF6B6B",
        "input_bg":     "#1E2D40",
        "input_fg":     "#C8D8E8",
        "spin_bg":      "#1E2D40",
        "spin_fg":      "#C8D8E8",
        "list_bg":      "#162030",
        "list_fg":      "#C8D8E8",
        "list_sel":     "#FF6B6B",
    }
